### **Imports**

In [59]:
import os
import pandas as pd
import spacy
import spacy.cli

from datasets import load_dataset
from utils import normaliza_texto

### **Datasets Direito**

#### **Normalização**

In [39]:
# JurisTCU
dataset = load_dataset("LeandroRibeiro/JurisTCU", data_files="doc.csv")
df_juris_tcu = dataset["train"].to_pandas()
display(df_juris_tcu.head())

Repo card metadata block was not found. Setting CardData to empty.

,KEY,NUMACORDAO,ANOACORDAO,COLEGIADO,AREA,TEMA,SUBTEMA,ENUNCIADO,EXCERTO,NUMSUMULA,...,AUTORTESE,FUNCAOAUTORTESE,TIPOPROCESSO,TIPORECURSO,INDEXACAO,INDEXADORESCONSOLIDADOS,PARAGRAFOLC,REFERENCIALEGAL,PUBLICACAOAPRESENTACAO,PARADIGMATICO
0,85434,358.0,2020.0,Plenário,Finanças Públicas,Regime Próprio de Previdência Social,Pensão,<b>SÚMULA TCU 43 (REVOGADA) : </b><s>As pensõe...,<b>Relatório:</b></p><p>Trata-se de estudo ela...,NaN,...,RAIMUNDO CARREIRO,RELATOR,ADMINISTRATIVO,NaN,"[Súmula, Guanabara, Custeio, Bombeiro militar,...",AREA: Finanças Públicas ; TEMA: Regime Próprio...,NaN,NaN,NaN,SUMULA
1,85447,358.0,2020.0,Plenário,Finanças Públicas,Transferências constitucionais e legais,Fundo de participação,<b>SÚMULA TCU 99 (REVOGADA) :</b> <s>Não pode ...,<b>Relatório:</b></p><p>Trata-se de estudo ela...,NaN,...,RAIMUNDO CARREIRO,RELATOR,ADMINISTRATIVO,NaN,"[Súmula, Fundo de Participação dos Municípios,...",AREA: Finanças Públicas ; TEMA: Transferências...,NaN,[Constituição Federal 1967 Art. 25 Congresso N...,NaN,SUMULA
2,85445,358.0,2020.0,Plenário,Finanças Públicas,Transferências constitucionais e legais,Fundo de participação,<b>SÚMULA TCU 84 (REVOGADA) :</b> <s>Restabele...,<b>Relatório:</b></p><p>Trata-se de estudo ela...,NaN,...,RAIMUNDO CARREIRO,RELATOR,ADMINISTRATIVO,NaN,"[Gestor sucessor, Fundo de Participação dos Mu...",AREA: Finanças Públicas ; TEMA: Transferências...,NaN,[Constituição Federal 1967 Art. 25 Congresso N...,NaN,SUMULA
3,85437,358.0,2020.0,Plenário,Finanças Públicas,Regime Próprio de Previdência Social,Aposentadoria,<b>SÚMULA TCU 104 (REVOGADA) :</b> <s>Não pode...,<b>Relatório:</b></p><p>Trata-se de estudo ela...,NaN,...,RAIMUNDO CARREIRO,RELATOR,ADMINISTRATIVO,NaN,"[Pensão, Guanabara, Acréscimo, Súmula, Proventos]",AREA: Finanças Públicas ; TEMA: Regime Próprio...,NaN,NaN,NaN,SUMULA
4,85444,358.0,2020.0,Plenário,Finanças Públicas,Transferências constitucionais e legais,Fundo de participação,<b>SÚMULA TCU 63 (REVOGADA) :</b> <s>É lícita ...,<b>Relatório:</b></p><p>Trata-se de estudo ela...,NaN,...,RAIMUNDO CARREIRO,RELATOR,ADMINISTRATIVO,NaN,"[Súmula, Fundo de Participação dos Municípios,...",AREA: Finanças Públicas ; TEMA: Transferências...,NaN,NaN,NaN,SUMULA

In [40]:
display(df_juris_tcu["EXCERTO"].iloc[0])

'<b>Relatório:</b></p><p>Trata-se de estudo elaborado pela Secretaria das Sessões (Seses) , para avaliar a utilidade e a pertinência dos enunciados da súmula de jurisprudência do Tribunal de Contas da União referentes aos grupos temáticos denominados "Estado da Guanabara" e "Fundos de Participação".</p><p>2. No âmbito da Seses, foram analisadas dez propostas relativas à temática "Estado da Guanabara" (peça 1) e sete referentes ao tema "Fundos de Participação" (peça 2) , opinando a unidade pelo cancelamento de dezesseis enunciados.</p><p>3. O feito foi submetido à Comissão Permanente de Jurisprudência deste Tribunal, composta pelos Ministros Benjamin Zymler, Augusto Nardes e Aroldo Cedraz, sob a presidência do primeiro, sendo relatado, no âmbito da comissão, pelo Ministro Augusto Nardes, cujas conclusões, acolhidas de modo unânime pelos pares, estão assim resumidas no parecer à peça 5:</p><p>"<i>a conveniência e a oportunidade do <b>cancelamento das Súmulas nº s 42, 43, 44, 45, 104, 119, 120, 121 e 161, do grupo temático \'Estado da Guanabara\', e nº s 50, 62, 63, 84, 88, 99 e 155, do grupo temático \'Fundos de Participação\'</b>, é decorrência lógica da dissonância que elas apresentam, quer em relação à legislação vigente quer em relação à atual jurisprudência desta Corte</i>".</p><p>[...]</p><p>5. Para uma compreensão mais detalhada das razões que fundamentam a proposta uniforme da Seses e da Comissão Permanente de Jurisprudência, reproduzo os anexos das instruções às peças 1 e 2, da Diretoria de Jurisprudência da Secretaria das Sessões:</p><p>  <b>grupo temático "Estado da Guanabara" (peça 1) </b></p><p><b>1. Enunciados com proposta de cancelamento</b></p><p><b>1.1 Enunciados superados</b></p><p>[...]</p><table><tbody><tr>\t<td><p><b>Súmula</b></p></td>\t<td><p>43</p></td></tr><tr>\t<td><p><b>Enunciado</b></p></td>\t<td><p>As pensões deferidas antes de 21/10/69, aos dependentes do pessoal, reformado, ou em atividade, da Polícia Militar e do Corpo de Bombeiros, transferido para o Estado da Guanabara, devem ser custeadas pela União, cabendo, porém, ao referido Estado a responsabilidade integral do pagamento decorrente dos reajustamentos posteriores.</p></td></tr><tr>\t<td><p><b>Ano de edição</b></p></td>\t<td><p>1973</p></td></tr><tr>\t<td><p><b>Análise</b></p></td>\t<td><p>Nas bases pesquisadas não foi localizada menção à súmula, tampouco julgados aplicando a respectiva tese.</p><p>A Lei 10.486/2002 torna superado o presente enunciado sumular ao estabelecer que compete à União o pagamento dos inativos e pensionistas do antigo Distrito Federal, independentemente da data de inativação ou de instituição da pensão, e dispor sobre a estrutura remuneratória e as demais vantagens devidas ao pessoal militar do antigo DF.</p><p>Na base do TCU, embora não haja menções à súmula 43, foram encontrados acórdãos referentes a pensões instituídas relativas ao pessoal transferido para o antigo Estado da Guanabara. Nenhum julgado, entretanto, amolda-se ao entendimento sumulado. </p><p>Do exposto, considerando a edição da Lei 10.486/2002, somado ao fato de que os normativos elencados nos fundamentos legais da súmula já se encontram revogados em sua quase totalidade, e da ausência, nas últimas décadas, de decisões do TCU que mencionem a súmula, propõe-se o cancelamento do verbete da Súmula de jurisprudência do TCU.</p></td></tr></tbody></table><p><b>Voto:</b></p><p>6. Após analisar a matéria, não tenho reparos às conclusões da unidade técnica e da Comissão Permanente de Jurisprudência, nos termos do bem lançado parecer do Ministro Augusto Nardes, igualmente coligido no Relatório, cujos fundamentos adoto como razões de decidir.</p><p><b>Acórdão:</b></p><p>9.1 cancelar os seguintes Enunciados da Súmula de Jurisprudência do Tribunal de Contas da União, porque dissonantes do ordenamento legal contemporâneo e ausentes da jurisprudência desta Corte de Contas na última década, em função do longo tempo decorrido desde as suas respectivas publicações;</p><p>9.1.1 nos 42, 43, 44, 45, 104, 119, 120, 121 e 161, vinculados ao grupo temático "Estado da Guanabara;</p><p>9.1.2  nos 50, 62, 63, 84, 88, 99 e 155, vinculados ao grupo temático "Fundos de Participação";</p><p>9.2 nos termos do art. 16 da Resolução-TCU 46/1996, ficam vagos, com nota de cancelamento, os números das súmulas ora revogadas; </p><p>9.3 nos termos do art. 89 do Regimento Interno deste Tribunal, determinar a publicação deste acórdão no Diário Oficial da União e no Boletim do Tribunal de Contas da União;'

In [41]:
df_juris_tcu['texto'] = df_juris_tcu['EXCERTO'].apply(normaliza_texto)

In [42]:
display(df_juris_tcu["texto"].iloc[0])

'relatoriotratase de estudo elaborado pela secretaria das sessoes seses  para avaliar a utilidade e a pertinencia dos enunciados da sumula de jurisprudencia do tribunal de contas da uniao referentes aos grupos tematicos denominados estado da guanabara e fundos de participacao no ambito da seses foram analisadas dez propostas relativas a tematica estado da guanabara peca  e sete referentes ao tema fundos de participacao peca   opinando a unidade pelo cancelamento de dezesseis enunciados o feito foi submetido a comissao permanente de jurisprudencia deste tribunal composta pelos ministros benjamin zymler augusto nardes e aroldo cedraz sob a presidencia do primeiro sendo relatado no ambito da comissao pelo ministro augusto nardes cujas conclusoes acolhidas de modo unanime pelos pares estao assim resumidas no parecer a peca a conveniencia e a oportunidade do cancelamento das sumulas nº s         e  do grupo tematico estado da guanabara e nº s       e  do grupo tematico fundos de participacao e decorrencia logica da dissonancia que elas apresentam quer em relacao a legislacao vigente quer em relacao a atual jurisprudencia desta corte para uma compreensao mais detalhada das razoes que fundamentam a proposta uniforme da seses e da comissao permanente de jurisprudencia reproduzo os anexos das instrucoes as pecas  e  da diretoria de jurisprudencia da secretaria das sessoes  grupo tematico estado da guanabara peca   enunciados com proposta de cancelamento enunciados superados\tsumula\t\tenunciado\tas pensoes deferidas antes de  aos dependentes do pessoal reformado ou em atividade da policia militar e do corpo de bombeiros transferido para o estado da guanabara devem ser custeadas pela uniao cabendo porem ao referido estado a responsabilidade integral do pagamento decorrente dos reajustamentos posteriores\tano de edicao\t\tanalise\tnas bases pesquisadas nao foi localizada mencao a sumula tampouco julgados aplicando a respectiva tesea lei  torna superado o presente enunciado sumular ao estabelecer que compete a uniao o pagamento dos inativos e pensionistas do antigo distrito federal independentemente da data de inativacao ou de instituicao da pensao e dispor sobre a estrutura remuneratoria e as demais vantagens devidas ao pessoal militar do antigo dfna base do tcu embora nao haja mencoes a sumula  foram encontrados acordaos referentes a pensoes instituidas relativas ao pessoal transferido para o antigo estado da guanabara nenhum julgado entretanto amoldase ao entendimento sumulado do exposto considerando a edicao da lei  somado ao fato de que os normativos elencados nos fundamentos legais da sumula ja se encontram revogados em sua quase totalidade e da ausencia nas ultimas decadas de decisoes do tcu que mencionem a sumula propoese o cancelamento do verbete da sumula de jurisprudencia do tcuvoto apos analisar a materia nao tenho reparos as conclusoes da unidade tecnica e da comissao permanente de jurisprudencia nos termos do bem lancado parecer do ministro augusto nardes igualmente coligido no relatorio cujos fundamentos adoto como razoes de decidiracordao cancelar os seguintes enunciados da sumula de jurisprudencia do tribunal de contas da uniao porque dissonantes do ordenamento legal contemporaneo e ausentes da jurisprudencia desta corte de contas na ultima decada em funcao do longo tempo decorrido desde as suas respectivas publicacoes nos         e  vinculados ao grupo tematico estado da guanabara  nos       e  vinculados ao grupo tematico fundos de participacao nos termos do art  da resolucaotcu  ficam vagos com nota de cancelamento os numeros das sumulas ora revogadas  nos termos do art  do regimento interno deste tribunal determinar a publicacao deste acordao no diario oficial da uniao e no boletim do tribunal de contas da uniao'

In [43]:
# PortugueseLegalSentences
dataset = load_dataset("rufimelo/PortugueseLegalSentences-v3")
df_portuguese_legal_sentences = dataset["train"].to_pandas()
display(df_portuguese_legal_sentences.head())

   Unnamed: 0                                               text
0           0  Deve a Ré ser condenada a pagar ao Autor a dif...
1           1  O valor equivalente a 9/12 de uma remuneração,...
2           2  O Acórdão recorrido está, salvo o devido respe...
3           3  Há, por isso, erro de julgamento quando o Trib...
4           4  Ora é pacificamente aceite que na tarefa de qu...

In [44]:
display(df_portuguese_legal_sentences['text'].iloc[0])

'Deve a Ré ser condenada a pagar ao Autor a diferença entre os vencimentos pagos desde julho de 2011 e o vencimento que venha a ser determinado nos termos dos pedidos formulados em ou, aos quais deverão acrescer juros de mora desde a data de vencimento de cada uma das prestações até integral pagamento, a liquidar em execução de sentença ou após a entrega dos documentos requeridos a final;'

In [45]:
df_portuguese_legal_sentences['texto'] = df_portuguese_legal_sentences['text'].apply(normaliza_texto)

In [46]:
display(df_portuguese_legal_sentences['texto'].iloc[0])

'deve a re ser condenada a pagar ao autor a diferenca entre os vencimentos pagos desde julho de  e o vencimento que venha a ser determinado nos termos dos pedidos formulados em ou aos quais deverao acrescer juros de mora desde a data de vencimento de cada uma das prestacoes ate integral pagamento a liquidar em execucao de sentenca ou apos a entrega dos documentos requeridos a final'

In [47]:
dataset = load_dataset("eduagarcia/oab_exams")
df_oab_exams = pd.DataFrame(dataset['train'])
display(df_oab_exams.head())

,id,question_number,exam_id,exam_year,question_type,nullified,question,choices,answerKey
0,2010-01_1,1,2010-01,2010,ETHICS,False,Júlio e Lauro constituíram o mesmo advogado pa...,"{'text': ['optar, com prudência e discerniment...",A
1,2010-01_2,2,2010-01,2010,ETHICS,False,"Mário, advogado regularmente inscrito na OAB, ...",{'text': ['Ainda que se reabilite criminalment...,D
2,2010-01_3,3,2010-01,2010,ETHICS,False,De acordo com o Estatuto da Advocacia e da OAB...,{'text': ['decisão não unânime proferida por c...,A
3,2010-01_4,4,2010-01,2010,ETHICS,False,Assinale a opção correta de acordo com as disp...,{'text': ['O compromisso que o requerente à in...,A
4,2010-01_5,5,2010-01,2010,ETHICS,False,"Acerca das infrações e sanções disciplinares, ...",{'text': ['Considere que uma advogada inscrita...,B

In [48]:
display(df_oab_exams['question'].iloc[0])

'Júlio e Lauro constituíram o mesmo advogado para, juntos, ajuizarem ação de interesse comum. No curso do processo, sobrevieram conflitos de interesse entre os constituintes, tendo Júlio deixado de concordar com Lauro com relação aos pedidos.\nNessa situação hipotética, deve o advogado'

In [49]:
df_oab_exams['texto'] = df_oab_exams['question'].apply(normaliza_texto)

In [50]:
display(df_oab_exams['texto'].iloc[0])

'julio e lauro constituiram o mesmo advogado para juntos ajuizarem acao de interesse comum no curso do processo sobrevieram conflitos de interesse entre os constituintes tendo julio deixado de concordar com lauro com relacao aos pedidos nessa situacao hipotetica deve o advogado'

In [57]:
# Concatenando apenas as colunas texto dos três dataframes
df_corpus_direito = pd.concat([
    df_juris_tcu['texto'],
    df_portuguese_legal_sentences['texto'],
    df_oab_exams['texto']
], ignore_index=True).to_frame(name="texto")

display(df_corpus_direito.head())

                                               texto
0  relatoriotratase de estudo elaborado pela secr...
1  relatoriotratase de estudo elaborado pela secr...
2  relatoriotratase de estudo elaborado pela secr...
3  relatoriotratase de estudo elaborado pela secr...
4  relatoriotratase de estudo elaborado pela secr...

In [58]:
df_corpus_direito.info()

<class 'pandas.DataFrame'>
RangeIndex: 418255 entries, 0 to 418254
Data columns (total 1 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   texto   418255 non-null  str
dtypes: str(1)
memory usage: 173.5 MB

#### **Tokenização**

In [60]:
#Carregando o pacote e o texto
spacy.cli.download("pt_core_news_sm")
nlp = spacy.load("pt_core_news_sm")

✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [ ]:
tokens_lista = []

print(f"Iniciando a tokenização de {len(df_corpus_direito)} linhas...")
print("Desativando componentes desnecessários para acelerar o processo...")

with nlp.select_pipes(disable=["parser", "ner", "lemmatizer"]):
    for doc in nlp.pipe(df_corpus_direito['texto'].astype(str), batch_size=2000, n_process=-1):
        tokens_limpos = [token.text.lower() for token in doc if not token.is_punct and not token.is_space]
        tokens_lista.append(tokens_limpos)

Iniciando a tokenização de 418255 linhas...
Desativando componentes desnecessários para acelerar o processo...

In [ ]:
# Se for um DataFrame, cria a coluna:
df_corpus_direito["tokens"] = tokens_lista

print("Tokenização concluída com sucesso!")

#### **Filtragem Tokens Raros**

#### **Construção do vocabulário**

#### **Salvamento dataset**

In [ ]:
base_dir = os.getcwd()
corpus_direito_path = os.path.join(base_dir,"..","datasets", "corpus_direito_tratado.csv")
print(f"Caminho para salvar o corpus tratado: {corpus_direito_path}")

# Salvando o df_corpus em um arquivo CSV
df_direito.to_csv(corpus_direito_path, index=False)

Caminho para salvar o corpus tratado: c:\projects\t2_introducao_pln_word2vec_similarity\src\..\datasets\corpus_direito_tratado.csv

#### **Datasets Tecnologia**

#### **Normalização**

#### **Tokenização**

#### **Filtragem Tokens Raros**

#### **Construção do vocabulário**

#### **Salvamento dataset**

In [ ]:
corpus_ti_path = os.path.join(base_dir,"..","datasets", "corpus_tecnologia_tratado.csv")
print(f"Caminho para salvar o corpus tratado: {corpus_ti_path}")

# Salvando o df_corpus em um arquivo CSV
df_corpus_ti.to_csv(corpus_ti_path, index=False)